doocs/md

- src/api/file.js
- src/assets/scripts/renderers/wx-renderer.js
- src/assets/scripts/uploadImageFile.js
- src/components/CodemirrorEditor/uploadImgDialog.vue
- src/store/imageApi.js
- src/store/index.js
> feat: upload config

- src/assets/less/theme.less
- src/components/CodemirrorEditor/aboutDialog.vue
- src/components/CodemirrorEditor/insertForm.vue
- src/components/CodemirrorEditor/resetDialog.vue
- src/components/CodemirrorEditor/rightClickMenu.vue
- src/components/CodemirrorEditor/uploadImgDialog.vue
> feat: style fix

- .gitignore
- mm.config.js
> feat: Support upload to local directory

- src/store/index.js
支持以下快捷键
- `Ctrl + B`: 加粗选中文本
- `Ctrl + D`: 删除选中文本
- `Ctrl + I`: 倾斜选中文本
> feat: support some keyboard shortcuts

- package.json
- sass 在目前项目中没有使用到，目前项目中使用的是 less
- sass 导致了 [#112](https://github.com/doocs/md/pull/112#issuecomment-985246677) 中的问题
> fix: Delete sass-loader

- src/components/CodemirrorEditor/rightClickMenu.vue
- 调整 HTML，使结构更贴合标签语义
- 移除部分不会生效的 CSS
> perf: more appropriate HTML structure

- src/router/index.js
- src/views/CodemirrorEditor.vue
- src/views/index.vue
> chore: move file

- src/components/CodemirrorEditor/uploadImgDialog.vue
> perf: eliminate scroll bars

- .eslintrc.js
- package.json
> chore: add an eslint configuration file

- src/assets/scripts/util.js
- src/components/CodemirrorEditor/aboutDialog.vue
- src/components/CodemirrorEditor/header.vue
- src/components/CodemirrorEditor/insertForm.vue
- src/components/CodemirrorEditor/resetDialog.vue
- src/views/CodemirrorEditor.vue
- 提供公共函数 & 使用合适的参数名称
- 统一导出函数声明
- 优化部分 JSDoc 注解
> chore: organize comments and formatting

- src/components/CodemirrorEditor/aboutDialog.vue
- src/components/CodemirrorEditor/resetDialog.vue
- src/views/index.vue
> pref: optimizing css

- package-lock.json
- package.json
> build: release v1.5.9

- src/components/Loading.vue
- src/views/CodemirrorEditor.vue
- src/views/index.vue
- 恢复移除的 css 代码，并将其并入 `<Loading>` 组件当中
- 动画控制迁移至 `<Loading>`
> fix: the lost animation

- src/components/RunLoading.vue
> perf: simplified RunLoading structure

- src/components/CodemirrorEditor/EditorHeader.vue
> chore: remove `size`

- src/components/CodemirrorEditor/EditorHeader/StyleOptionMenu.vue
> fix: margin anomaly

- src/assets/scripts/converter.js
- src/components/CodemirrorEditor/EditorHeader/index.vue
- src/store/index.js
- src/views/CodemirrorEditor.vue
> feat: add Mac-style code blocks

- src/components/CodemirrorEditor/CssEditor.vue
- src/views/CodemirrorEditor.vue
> perf: separation of components

- src/components/CodemirrorEditor/EditorHeader/PostInfoDialog.vue
- src/components/CodemirrorEditor/EditorHeader/index.vue
> perf: separation dialog component

- src/views/CodemirrorEditor.vue
> fix: abnormal hyperlink

- README.md
See discussion #5 for more details
> docs: update user list

- src/components/CodemirrorEditor/UploadImgDialog.vue
> fix:  localStorage of formQiniu

- src/stores/index.js
支持一下Mac电脑上的快捷键体验，增加将文本变为内置代码块快捷 Cmd-L  or  Ctrl-L
> feat: Mac电脑上快捷键特性支持

- package-lock.json
- package.json
- public/index.html
- src/assets/scripts/renderers/wx-renderer.js
- src/components/CodemirrorEditor/EditorHeader/index.vue
- src/main.js
> feat: support for `$` rendering katex

- src/components/CodemirrorEditor/EditorHeader/index.vue
- src/stores/index.js
- src/views/CodemirrorEditor.vue
> feat: optional edit area location

- src/assets/scripts/renderers/wx-renderer.js
> fix: code block rendering exception

- src/components/CodemirrorEditor/EditorHeader/StyleOptionMenu.vue
> fix: unused font

- src/assets/scripts/renderers/wx-renderer.js
> feat: supports image titles as comment

- src/assets/less/app.less
- src/assets/scripts/themes/default-theme.js
> fix: word break

- src/components/CodemirrorEditor/InsertFormDialog.vue
- src/views/CodemirrorEditor.vue
修复插入表格和图片时，出现不可编辑、编辑错位和撤回导致崩溃等问题。
> fix: error of insert action

- src/assets/less/theme.less
> style: dark mode of editor

- index.html
- package-lock.json
- package.json
- src/utils/wx-renderer.js
- 将 mermaid 用法从 cdn 改为 npm
- 修复首次渲染时，多个 mermaid 可能产生的错误
> chore: change mermaid from cdn to npm

- src/utils/wx-renderer.js
> fix: render of list

- README.md
Visit https://doocs-md.pages.dev
> docs: add a backup site

- src/stores/index.js
> fix: font-size of init

- src/components/CodemirrorEditor/EditorHeader/StyleDropdown.vue
- src/components/CodemirrorEditor/EditorHeader/index.vue
- src/utils/index.ts
> feat: add more style option

- package-lock.json
- src/utils/file.ts
> fix: Cannot read properties of undefined (reading 'content')

- src/components/CodemirrorEditor/EditorHeader/index.vue
- src/stores/index.ts
- src/types/index.ts
- src/utils/renderer.ts
> feat: support for indent options

- src/stores/index.ts
> fix: formatted document

- package-lock.json
- package.json
> bugfix: 解决mermaid 图绘制失败的问题,mermaid库升级解决

- src/assets/example/markdown.md
- src/components/CodemirrorEditor/EditorHeader/index.vue
> fix: copy of mermaid

- vite.config.ts
> fix: file name of build

- src/utils/index.ts
修复margin-top 被正则替换成margin-transform问题
> fix: fix regex expression

- src/components/CodemirrorEditor/CssEditor.vue
- src/components/CodemirrorEditor/EditorHeader/index.vue
- src/components/CodemirrorEditor/PostSlider.vue
- src/components/CodemirrorEditor/RightSlider.vue
- src/views/CodemirrorEditor.vue
- 调整暗色模式下元素配色，提升辨识度
- 增加边框，便于区分边界
- 移除最外层元素边距，使编辑区与浏览区直接贴边
> style: optimize the color scheme

- src/config/theme.ts
> feat: add new theme options

- example/.gitignore
- example/README.md
- example/package.json
- example/wrangler.toml
> feat: cloudflare workers proxy

- src/components/CodemirrorEditor/EditorHeader/PostInfo.vue
> fix: resolve issue with article publishing plugin

- src/config/theme.ts
> fix: mixed Chinese and English typesetting

- src/modules/build-extension.ts
As mentioned earlier, CDN JS cannot be loaded from extension pages. For more details, please refer to this [article](https://mp.weixin.qq.com/s/jgaDKNi0bY8HaPtL0-7zTw).
cdn js无法在扩展中加载，需要做一次本地化处理，参考之前的[文章](https://mp.weixin.qq.com/s/jgaDKNi0bY8HaPtL0-7zTw)
本次改动参考了vite plugin官方文档，https://cn.vite.dev/guide/api-plugin
调整本地化cdn js的vite plugin加载顺序，改用`transformIndexHtml`方案，确保在这些的插件执行后
```js
analytics: {
id: `G-7NZL3PZ0NK`,
},
}),
```
才执行本地化cdn js的插件。
> feat: support gtag cdn js in extension

- package-lock.json
- package.json
> chore: upgrade vite version

- src/config/theme.ts
> fix: image preview not match publication

- src/assets/example/theme-css.txt
- src/config/theme.ts
- src/types/index.ts
- src/utils/MDKatex.d.ts
- src/utils/MDKatex.js
- src/utils/index.ts
- src/utils/renderer.ts
> feat: support setting style of katex

- src/components/CodemirrorEditor/PostSlider.vue
> fix: incorrect sorting of Chinese

- src/assets/less/app.less
- src/views/CodemirrorEditor.vue
> fix: preview width

- src/components/CodemirrorEditor/EditorHeader/FileDropdown.vue
- src/components/CodemirrorEditor/EditorStateDialog.vue
- src/config/store.ts
- src/stores/index.ts
基本完成页面的构建，但有瑕疵，不能立刻回显自定义的css样式和覆盖的文章内容，需要刷新后展示。页面排版的设置可以及时回显
> Export/import store settings (JSON)

- src/components/ai/AIAssistantPanel.vue
在发送消息时，添加了 `AbortController` 来处理请求中止，确保在重置消息时能够正确中止未完成的请求。同时，优化了消息更新的逻辑，确保在消息发生变化时不会错误地更新最后一条消息。
> fix(AIAssistantPanel): 在点击删除按钮后主动中止当前消息请求，避免错误更新最后一条信息

- src/components/ai/AIConfig.vue
温度字段增加tooltip提示来提醒用户字段含义，提升用户体验
> feat(ui): add tooltip to explain temperature setting in AIConfig

- src/components/ai/AIAssistantPanel.vue
> style: update ai panel

- src/components/ai/AIAssistantPanel.vue
Added full-text quote feature to AI chat
> Added full-text quote feature to AI chat

- src/components/AIPolish/AIPolishPopover.vue
- src/components/ai/AIAssistantPanel.vue
- 支持编辑消息
- AI 未响应时，展示为“思考中...”
- 优化引用全文
> feat(ai): edit msg in chat panel

- src/stores/index.ts
- src/views/CodemirrorEditor.vue
Add the function of clearing the full text
> Add the function of clearing the full text

- src/components/CodemirrorEditor/EditorHeader/index.vue
- 支持复制MD文本
当需要把md文本复制出来粘贴到其他平台发布时，没有一键复制的功能。特别是在移动端时复制困难。
在移动端使用时：
- md编辑器中长按文字后会立即弹出菜单，很难操作选中全部md文本
- 使用手机输入法自带的全选功能时，会无法选中全部md文本进行复制
点击输入法的全选后只选中了一部分，如下图：
下拉选择：
复制后提示：
> feat: support copying MD text

- src/config/theme.ts
- src/utils/MDKatex.js
- src/utils/renderer.ts
对于长内联公式支持左右滑动浏览
$\int_0^{\infty} \frac{\sin(x)}{x}dx \cdot \sum_{n=1}^{\infty} \frac{1}{n^2} \cdot \prod_{i=1}^{100} (1 - \frac{1}{i^2}) \cdot \lim_{x \to \infty}\left(1+\frac{1}{x}\right)^x \cdot \frac{d}{dx}\left[\int_0^x \sqrt{1+t^4}dt\right] \cdot \oint_C \frac{1}{z-z_0}dz \cdot \sum_{k=0}^{\infty}\binom{n}{k}p^k(1-p)^{n-k} \cdot \sqrt[n]{\prod_{i=1}^{n}x_i}$
修改前：
修改后：
> Support scrolling for long inline formula

- src/components/CodemirrorEditor/EditorHeader/index.vue
- src/components/CodemirrorEditor/PostSlider.vue
- 优化暗色模式文章侧边栏表现不佳的样式
- 切换按钮尺寸调整
> style: update post-slider and toggle button

- src/utils/MDKatex.js
> fix: block rule

- src/stores/index.ts
- 修复文档重置时，可能出现的内容错位
- 修复文档清空时，编写出现异常
> fix: reset and clear function error

- package-lock.json
- package.json
- src/components/AIPolish/AIPolishPopover.vue
- src/components/CodemirrorEditor/EditorHeader/index.vue
- src/components/CodemirrorEditor/PostItem.vue
- src/components/CodemirrorEditor/PostSlider.vue
- src/components/ai/AIAssistantPanel.vue
- src/components/ui/resizable/ResizableHandle.vue
- src/components/ui/resizable/ResizablePanelGroup.vue
- src/components/ui/resizable/index.ts
- src/stores/index.ts
- src/views/CodemirrorEditor.vue
> 要么清空子文件夹的 `parentId`，要么禁止该行为
> feat: support folders

- package-lock.json
- package.json
- src/entrypoints/background.ts
- wxt.config.ts
- update wxt to v0.20.7
- sidepanel 采用常驻方式
- 在Firefox 使用快捷键方式打开sidebar
后续wxt/browser api兼容后，可进一步优化代码
> feat: update wxt dependency to 0.20.7 and add side panel configuration

- src/components/CodemirrorEditor/EditorStateDialog.vue
- 固定「配置导出」标题区域
- 控制「配置导出」全屏窗口的滚动条生效范围，以便于使用「一键复制」
> style: optimize the scroll bar of state dialog

- src/components/CodemirrorEditor/EditorStateDialog.vue
> fix: initialization logic of the status dialog

- src/components/CodemirrorEditor/PostItem.vue
- src/components/CodemirrorEditor/RightSlider.vue
- src/components/ai/AIAssistantPanel.vue
- 右侧面板视觉调整，选中的选项更明显
- 重置改为危险色
- 垃圾桶 icon 更换
> style: optimize UI style

- src/stores/index.ts
> fix: reading time has not been updated

- src/components/CodemirrorEditor/InsertMpCardDialog.vue
- 加入表单验证
- 添加插入提醒
- 弃用未标记前缀的数据
> refactor: add form validation for InsertMpCardDialog

- src/components/CodemirrorEditor/EditorContextMenu.vue
- src/views/CodemirrorEditor.vue
> refactor: extract editor context menu into separate component

- src/components/CodemirrorEditor/Footer.vue
- src/stores/index.ts
- src/views/CodemirrorEditor.vue
> feat: add dedicated Footer component for reading time display

- src/components/CodemirrorEditor/EditorHeader/FileDropdown.vue
- src/stores/index.ts
- src/utils/index.ts
尝试过 html2pdf.js 导出，但是效果非常差，因此使用浏览器自带打印导出 pdf。
Implements #230
Implements #844
> feat: support export pdf

- src/components/CodemirrorEditor/EditorHeader/FileDropdown.vue
- src/components/CodemirrorEditor/EditorStateDialog.vue
- src/stores/index.ts
- src/types/index.ts
- src/utils/MDAlert.ts
- src/utils/index.ts
抽象下载方法，实现导出无样式 HTML
Support #266
> feat: export pure html without style

- src/assets/example/theme-css.txt
- src/config/theme.ts
- src/types/index.ts
- src/utils/MDAlert.ts
- 新增 `info` 类型
- 支持 `vuepress/vitepress` 风格 GFM 块
Closes #783
> feat: support vuepress/vitepress style GFM

- src/modules/build-extension.ts
> fix: remove  bad split chunks

- index.html
> feat: add timeout tip for editor loading

- apps/web/src/components/CodemirrorEditor/EditorHeader/index.vue
- apps/web/src/utils/index.ts
> fix: resolve SVG content loss when copying to WeChat by using modern Clipboard API

- package.json
https://github.com/antfu/node-modules-inspector
> chore: add inspector script to visualize node_modules

- CONTRIBUTING.md
- apps/web/vite.config.ts
- apps/web/wxt.config.ts
自定义 `vite-plugin-vue-devtools` 打开的编辑器
> chore: support launch editor in development

- apps/web/src/views/CodemirrorEditor.vue
dont show progress bar when pasting text
> fix: dont show progress bar when pasting text

- apps/web/src/components/ui/alert-dialog/AlertDialogContent.vue
> fix: alert dialog z-index
