doocs/md

- src/assets/less/theme.less
- src/assets/scripts/util.js
- src/pages/index/view/CodemirrorEditor.vue
复制按钮处对 HTML 的处理，在文件下载的时候，没有生效，这个结论基于我的尝试。
我的解决办法，是针对代码块部分的元素，首先获取到元素所有的样式属性，然后做成行内样式，最后再导出。
> fix: code style lost in downloaded html file

- README.md
- mm.config.js
- src/api/file.js
- src/assets/scripts/util.js
- src/components/CodemirrorEditor/uploadImgDialog.vue
在工具上没有提供预定义图床的情况下，你只需要自定义上传逻辑即可，这对于例如你不方便使用公共图床，而是使用自己的上传服务时非常有用。
你只需要在给定的函数中更改上传代码即可，为了方便，这个函数提供了可能使用的一些参数：
示例代码:
```js
const {file, util, okCb, errCb} = CUSTOM_ARG
const param = new FormData()
param.append('file', file)
util.axios.post('http://127.0.0.1:9000/upload', param, {
headers: { 'Content-Type': 'multipart/form-data' }
}).then(res => {
okCb(res.url)
}).catch(err => {
errCb(err)
})
// 提供的可用参数:
// CUSTOM_ARG = {
//   content, // 待上传图片的 base64
//   file, // 待上传图片的 file 对象
//   util: {
//     axios, // axios 实例
//     CryptoJS, // 加密库
//     OSS, // ali-oss
//     COS, // cos-js-sdk-v5
//     Buffer, // buffer-from
//     uuidv4, // uuid
//     qiniu, // qiniu-js
//     tokenTools, // 一些编码转换函数
//     getDir, // 获取 年/月/日 形式的目录
//     getDateFilename, // 根据文件名获取它以 时间戳+uuid 的形式
//   }, …
```
> feat: Custom upload logic

- vue.config.js
When `production` building, there is no need to build sourcemap , if build, the release size will increase by 10M+.
> chore: turn off source map at production env

- src/assets/scripts/util.js
> fix: rendering failed table

- src/components/CodemirrorEditor/RightClickMenu.vue
- src/store/index.js
- src/views/CodemirrorEditor.vue
- 从 vuex 当中抽离 `rightClickMenuVisible`，该值并不需要放入 Vuex 当中共享
- 使用 `visible` 替代 `value`
- 移除失效函数 `closeCB()`
> chore: migration rightClickMenuVisible 

- src/components/CodemirrorEditor/AboutDialog.vue
- src/components/CodemirrorEditor/InsertFormDialog.vue
- src/components/CodemirrorEditor/RightClickMenu.vue
- src/components/CodemirrorEditor/UploadImgDialog.vue
- src/views/CodemirrorEditor.vue
- 将 `value` 修改为 `visible`，并添加显式关闭方法
- 移除 `onmousedown` 事件，与显式关闭 `closeMenu()` 重叠
> chore: from value to visible

- src/assets/scripts/renderers/wx-renderer.js
- src/store/index.js
目前如果在list中写code，pre标签会被替换掉，导致code样式不正确
> fix: not replace <pre> in list

- package-lock.json
- package.json
minio 在 `7.1.0` 开始，使用了一些与当前项目不兼容的语法，如 `??`，导致项目无法启动成功。
通过将版本锁定到 `7.0.33`，得以解决。
> fix: unexpected token

- src/components/CodemirrorEditor/EditorHeader/index.vue
使用 Simulator 测试得知，低版本 Safari 无法兼容正则断言语法，并定位问题所在：
注释后：
close #196
> fix: locate the bug

- src/components/CodemirrorEditor/EditorHeader/index.vue
> fix: 保存后公式元素偏移

- .github/workflows/preview-deploy.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- src/stores/index.js
fix #285
原因：当设备处于深色模式时，公众号网页会生成了一些适配代码，最终导致渲染异常。
> fix: mac code block display exception

- src/assets/scripts/config.js
> feat: supports equal width fonts

- src/components/CodemirrorEditor/EditorHeader/index.vue
> fix: list rendering error

- src/components/CodemirrorEditor/CssEditor.vue
- src/stores/index.js
- 阻止空值命名
- 选中的 tab 可进行重命名操作
- 加入默认命名
- 调整 tab 样式
> feat: optimize custom css

- src/stores/index.ts
- src/utils/index.ts
> fix: font-size of theme

- src/config/theme.ts
- src/utils/renderer.ts
- 修复有序列表序号渲染错误
而在 marked 中：
- 无序列表嵌套有序列表样式错误
> fix: correct ordered list start number rendering

- README.md
- src/stores/index.ts
- src/utils/index.ts
> fix: export to html render abnormal

- src/components/CodemirrorEditor/UploadImgDialog.vue
- add required to form-item
- proxyOrigin is required when run in website
> feat: mp oss form update

- src/components/CodemirrorEditor/EditorHeader/index.vue
- src/components/CodemirrorEditor/PostSlider.vue
- src/stores/index.ts
- src/views/CodemirrorEditor.vue
> feat: init post list

- README.md
- src/assets/less/app.less
- src/components/CodemirrorEditor/PostSlider.vue
- src/stores/index.ts
- 预览框高度默认全屏
- 文章数量剩下 1 时，不展示删除按钮
> feat: update post slider

- src/assets/less/app.less
> fix: preview container height overflow

- src/assets/example/theme-css.txt
- src/config/theme.ts
- src/stores/index.ts
- src/types/index.ts
- src/utils/index.ts
- src/utils/renderer.ts
> feat: add to root container

- src/components/CodemirrorEditor/EditorHeader/PostInfo.vue
- src/components/CodemirrorEditor/EditorHeader/index.vue
- src/components/ui/back-top/BackTop.vue
- src/components/ui/back-top/index.ts
- src/views/CodemirrorEditor.vue
- Introduced a button to toggle dark mode using Moon and Sun icons.
- Add a BackTop component for improved navigation within the preview area.
- Add extension detection.
> feat: add dark mode toggle and enhance interaction in CodemirrorEditor 

- src/components/CodemirrorEditor/EditorHeader/PostInfo.vue
- src/components/CodemirrorEditor/EditorHeader/PostTaskDialog.vue
- src/types/index.ts
> feat: enhance post management

- package.json
- src/entrypoints/popup/App.vue
- wxt.config.ts
fix el-link
插件版本号改为follow web项目方式
配置支持firefox 打包方式
> feat: fix el-link

- src/utils/file.ts
调整了mpFileUpload方法的写法，
之前的`new Promise<string>(async (resolve, reject)`写法，这种async可能有问题。
> refactor: update mpFileUpload

- src/utils/file.ts
节省微信素材库使用额度。
根据官方文档，小图片上传到另外一个接口
https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Adding_Permanent_Assets.html
>5、"上传图文消息内的图片获取URL"接口所上传的图片，不占用公众号的素材库中图片数量的100000个的限制，图片仅支持jpg/png格式，大小必须在1MB以下。
> feat: update mp oss to save quota

- src/stores/index.ts
- src/utils/renderer.ts
- src/views/CodemirrorEditor.vue
> feat: support title navigation

- src/components/ui/back-top/BackTop.vue
- src/views/CodemirrorEditor.vue
fix #538 
Just move the `BackTop ` button into Preview.
Before:
After:
> feat: update BackTop button position.

- src/config/theme.ts
- src/views/CodemirrorEditor.vue
fix #611 
**before:**
**after:**
And fix a bug in #664 because I didn't consider the style in mobile type.
**before:**
**after:**
> fix: code style in `grace` and `simlpe` theme.

- src/utils/MDFootnotes.ts
- src/utils/renderer.ts
fix #579 
支持footnotes语法
但是脚注会和自动生成的“微信外链转底部引用”编号重复，也许需要提示用户分开使用。
> support footnotes syntax

- src/assets/less/theme.less
- src/stores/index.ts
Display the scrollbar of the CSS editor and save its visibility setting in the browser's localStorage.
> show css editor scroll.

- src/components/AIPolish/AIPolishPopover.vue
修改前：
AI工具箱输出的文字里面含有很多额外的说明内容
修改后
AI工具箱直接输出修改后的结果
> feat(AIPolishPopover): update system prompt to restrict output format

- src/components/AIPolish/AIPolishPopover.vue
当前在AI工具箱里面如果出现请求失败不会提示用户，增加了toast提示。同时处理在用户主动中止请求时不展示toast的特殊情况。
> feat(AIPolishPopover): display toast on request failure

- src/stores/index.ts
fix bug[#749 ]
在h2 strong时继承父级颜色
> fix: the background and font colors are the same when bolding the h2 title (#749)

- src/stores/index.ts
过滤时，保留 `<mp-common-profile>` 标签
> fix: add the `<mp-common-profile>` tag whitelist to DOMPurify

- src/views/CodemirrorEditor.vue
1. 修改了错误的命名，这里理论上应该是负责超链接，应该是link
2. 在添加完链接之后，光标将会移送至超链接的括号中间，而不是右边，优化了下体验
> Feat/optimized the link filling experience when ctrl+k

- wxt.config.ts
remove ga when run in extension
> feat: filter out 'vite-plugin-Radar' from Vite plugins

- src/components/CodemirrorEditor/PostSlider.vue
使用过子菜单添加文章后，导致后续顶部按钮的添加操作不会在根目录下生成。
> fix: `parentId` not reset

- src/modules/build-extension.ts
- wxt.config.ts
update manual chunks in build-extension
```ts
if (id.includes(`prettier`))
return `prettier`
if (id.includes(`katex`))
return `katex`
if (id.includes(`mermaid`))
return `mermaid`
if (id.includes(`cytoscape`))
return `cytoscape`
if (id.includes(`highlight.js`))
return `hljs`
```
> fix: update manualChunks handling in build configuration

- src/App.vue
- src/components/CodemirrorEditor/EditorHeader/index.vue
- 修复 toast 通知一直为亮色样式
- 移动 <Toaster> 至根组件
> fix: Toaster did not follow the theme of app

- src/modules/build-extension.ts
- wxt.config.ts
remove `define` option in `vite.config.ts`
build output files now are with the same hash in file names in each builds
> refactor: clean up output file naming in build configuration

- wxt.config.ts
> feat: add zip configuration to exclude specific source directories

- src/stores/index.ts
> fix: add null check for editor instance in post content watch

- package-lock.json
- package.json
- src/types/global.d.ts
- src/utils/renderer.ts
- 支持 GDScript 代码块高亮
- 扩展库没有 type，手动补充类型声明
- ESLint 会强制将字符串改为反引号，但类型声明不支持反引号写法，所以屏蔽
> feat: add GDScript syntax highlighting support for markdown rendering

- wxt.config.ts
打包firefox source code zip 时，过滤掉 `src/extension` 目录。
> fix: include src/extension directory in zip exclusion list

- packages/core/src/renderer/renderer-impl.ts
> fix: WeChat remove standalone spaces in code blocks

- packages/core/src/renderer/renderer-impl.ts
微信会移除单独 `span` 的空格，如以下标签会被剔除：
```html
<span leaf>&nbsp;</span>
```
因此需要将空格和 `span` 进行合并。
原来的正则表达式 `/(<span[^>]*>[^<]*<\/span>)(\s+)(<span[^>]*>)/g` 只匹配：
- 完整的第一个 `span` 标签
- 空格
- 第二个 `span` 标签的开始部分
增加两种情况：
1. 处理两个完整 `span` 标签之间的空格 `/(<span[^>]*>[^<]*<\/span>)(\s+)(<span[^>]*>[^<]*<\/span>)/g`：
- 匹配两个完整的 span 标签之间的空格
- 将空格移到第二个 span 标签内部
2. 处理 `span` 标签开始前的空格 `/(\s+)(<span[^>]*>)/g`
#894 
```yaml
jobs:
build:
runs-on: host
outputs:  # 声明作业的输出变量
datetime: ${{ steps.datetime.outputs.datetime }}
steps:
#.....省去拉取源码等其他配置....
- name: Cache dependencies
uses: http://git.luhome.com/actions/cache@v4
id: yarn-cache
with:
path: |
~/.cache/yarn
.next/cache
node_modules
key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
restore-keys: |
${{ runner.os }}-yarn-
```
```ts
// 测试代码
public test(): …
```
> fix: preserve spaces to prevent WeChat removal

- apps/web/src/assets/less/app.less
- apps/web/src/components/CodemirrorEditor/CssEditor.vue
- apps/web/src/components/CodemirrorEditor/EditorHeader/AboutDialog.vue
- apps/web/src/components/CodemirrorEditor/EditorHeader/EditDropdown.vue
- apps/web/src/components/CodemirrorEditor/EditorHeader/FileDropdown.vue
- apps/web/src/components/CodemirrorEditor/EditorHeader/FormatDropdown.vue
- apps/web/src/components/CodemirrorEditor/EditorHeader/HelpDropdown.vue
- apps/web/src/components/CodemirrorEditor/EditorHeader/StyleDropdown.vue
- apps/web/src/components/CodemirrorEditor/EditorHeader/index.vue
- apps/web/src/components/CodemirrorEditor/EditorStateDialog.vue
- apps/web/src/components/CodemirrorEditor/PostSlider/index.vue
- apps/web/src/components/CodemirrorEditor/RightSlider.vue
- apps/web/src/components/CodemirrorEditor/UploadImgDialog.vue
- apps/web/src/components/CustomUploadForm.vue
- apps/web/src/components/FormItem.vue
- apps/web/src/components/ui/dialog/DialogContent.vue
- apps/web/src/components/ui/popover/PopoverContent.vue
- apps/web/src/components/ui/select/SelectContent.vue
- apps/web/src/views/CodemirrorEditor.vue
- 左侧文章区域移至：文件 ---> 内容管理
- 移动端菜单适配
- 弹窗适配
- 内容管理 & 样式设置适配
> style: mobile adaptation

- apps/web/src/components/CodemirrorEditor/PostSlider/index.vue
> fix: link text break line
